[window]
# decorations = "None"

[font]
normal = { family = "Spleen 32x64"}
size = 11.5

# [font]
# normal = { family = "PxPlus IBM VGA8"}
# size = 11.5
# normal = { family = "Unifont"}
# normal = { family = "Terminus"}
# size = 12

[colors]
vi_mode_cursor = { text = '#1c1c1c', cursor = '#bcbcbc'}
cursor = { text = '#1c1c1c', cursor = '#bcbcbc'}

# [colors.primary]
# background = '0x181512'
# foreground = '0xbea492'
[colors.primary]
foreground = "#c5c8c6"
background = "#1d1f21"

[colors.normal]
black   = "#282a2e"
red     = "#a54242"
green   = "#8c9440"
yellow  = "#de935f"
blue    = "#5f819d"
magenta = "#85678f"
cyan    = "#5e8d87"
white   = "#707880"

[colors.bright]
black   = "#373b41"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"
# 
# [colors.primary]
# background = '#1c1c1c'
# foreground = '#bcbcbc'
# 
# [colors.normal]
# black =   '0x335d29'
# 
[keyboard]
bindings = [
    { key = "A", mode = "Vi", action = "ToggleViMode" },
]
